### ISSUE TITLE
3GPP cipher suites

### ISSUE THREAD

**Issue by ceco** [mordyovits/golang-crypto-tls#2]
Hi.

Is there support for the following suites:
TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 defined in RFC 5487
TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 defined in RFC 8442
TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384 defined in RFC 8442
Is it very hard to add these ?

Regards.

**Comment by mordyovits** [comment]
This fork already supports TLS_DHE_PSK_WITH_AES_128_GCM_SHA256, and the other two are not too hard to add.  But I'm not supporting this fork now, and the Go team is very against adding support for ciphers.

**Comment by ceco** [comment]
"Go team is very against adding support for ciphers" - why is that ? These ciphers are very important for mobile core networks.
So may be the best way is to make a c/c++ library and use it from Go ?

**Comment by mordyovits** [comment]
It's up to the people at Google, not me.  But Adam Langley explained his position here: https://www.imperialviolet.org/2016/05/16/agility.html
