### ISSUE TITLE
Why is SignatureScheme of ECDSAWithP256AndSHA256 defined as 0x0403? Is there any standard for deciding the scheme IDs?

### ISSUE THREAD

**Issue by FrozenFort** [mordyovits/golang-crypto-tls#3]
Why is SignatureScheme of ECDSAWithP256AndSHA256 defined as 0x0403? Is there any standard for deciding the scheme IDs?

**Comment by mordyovits** [comment]
You're asking the wrong person (this is a fork of the Go TLS stack).  But anyway, yes it's defined in the RFC:
https://tools.ietf.org/html/rfc8446#section-4.2.3
